name: concieltalk
description: Conciel, a new way of connecting.
publish_to: none
version: 1.20.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_dialog: ^1.9.0-x-macos-beta.1
  animations: ^2.0.7
  badges: ^3.1.2
  blurhash_dart: ^1.1.0
  callkeep: ^0.3.2
  chewie: ^1.3.6
  cloud_firestore: ^4.9.3
  collection: ^1.16.0
  connectivity_plus: ^4.0.1
  cubixd:
    git:
      url: git@github.com:Conciel/cubixd
      ref: main
  cupertino_icons: any
  desktop_drop: ^0.4.0
  desktop_lifecycle: ^0.1.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^9.0.2
  dynamic_color: ^1.6.0
  emoji_picker_flutter: ^1.5.1
  emoji_proposal: ^0.0.1
  emojis: ^0.9.9
  file_manager: ^1.0.2
  file_picker: ^5.3.0
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_app_lock: ^3.0.0
  flutter_arc_text: ^0.5.0
  flutter_background: ^1.2.0
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_callkeep: ^0.3.2
  flutter_contacts: ^1.1.7
  flutter_foreground_task: ^6.1.2
  flutter_highlighter: ^0.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^16.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_math_fork: ^0.7.1
  flutter_olm: ^1.2.0
  flutter_ringtone_player: ^3.1.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_typeahead: ^4.3.2
  flutter_web_auth_2: ^2.1.1
  flutter_webrtc: ^0.9.45
  fluttertoast: ^8.2.2
  future_loading_dialog: ^0.2.3
  geocoding: ^2.1.0
  geolocator: ^10.0.1
  google_maps_flutter: ^2.5.0
  google_maps_flutter_android: ^2.5.1
  google_maps_flutter_platform_interface: ^2.4.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  handy_window: ^0.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.0
  image_picker: ^1.0.0
  intl: any
  json_annotation: ^4.8.1
  just_audio: ^0.9.30
  just_audio_mpv: ^0.1.6
  latlong2: ^0.8.0
  linkify: ^5.0.0
  local_auth: ^2.1.6
  matrix: ^0.22.4
  mime: ^1.0.4
  native_imaging: ^0.1.0
  new_keyboard_shortcuts: ^0.1.4
  package_info_plus: ^4.0.0
  path_provider: ^2.0.9
  permission_handler: ^11.0.0
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  receive_sharing_intent: ^1.4.5
  record: ^4.4.4
  scroll_to_index: ^3.0.1
  settings_ui: ^2.0.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.1
  sliver_tools: ^0.2.12
  slugify: ^2.0.0
  swipe_to_action: ^0.2.0
  thumbnailer: ^2.2.0
  tor_detector_web: ^1.1.0
  tutorial_coach_mark: ^1.2.9
  uni_links: ^0.5.1
  unifiedpush: ^5.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.20
  vibration: ^1.7.4-nullsafety.0
  video_compress: ^3.1.1
  video_player: ^2.2.18
  video_thumbnail: ^0.5.3
  vrouter: ^1.2.0+21
  wakelock_plus: ^1.1.1
  webrtc_interface: ^1.0.13

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.7.0
  msix: ^3.6.2
  translations_cleaner: ^0.0.5

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/
    - assets/map_data/

  fonts:
    - family: Exo
      fonts:
        - asset: fonts/Exo-Regular.ttf
        - asset: fonts/Exo-Italic.ttf
          style: italic
        - asset: fonts/Exo-Bold.ttf
          weight: 700
    - family: ConcielIcons
      fonts:
        - asset: fonts/ConcielIcons.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto/RobotoMono-Regular.ttf
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

cider:
  link_template:
    tag: https://github.com/Conciel/conciel_talk/releases/tag/%tag% # initial release link template
    diff: https://github.com/Conciel/conciel_talk/compare/%from%...%to% # subsequent releases link template

msix_config:
  display_name: ConcielTalk
  publisher_display_name: ConcielTalk
  publisher: CN=Conciel, O=Head of integration, L=Matrix, S=Internet, C=EU
  identity_name: talk.conciel.concieltalk
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: concieltalk.im, matrix.to
  execution_alias: concieltalk
  sign_msix: false
  install_certificate: false
