// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ97OPJ8jpPPnNuEFK5QTZ7gForI--L5E',
    appId: '1:355943116384:web:cf264284c4dd3186711d05',
    messagingSenderId: '355943116384',
    projectId: 'conciel-talk',
    authDomain: 'conciel-talk.firebaseapp.com',
    storageBucket: 'conciel-talk.appspot.com',
    measurementId: 'G-Y02S08ZYDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYIEQnV1qraO7u-pinOVGQVCBpblEveWc',
    appId: '1:355943116384:android:7339fddfeba48e68711d05',
    messagingSenderId: '355943116384',
    projectId: 'conciel-talk',
    storageBucket: 'conciel-talk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhrgcvK8AfV-m06mAUegTx82u75tizPM',
    appId: '1:355943116384:ios:2218053ac18f7f49711d05',
    messagingSenderId: '355943116384',
    projectId: 'conciel-talk',
    storageBucket: 'conciel-talk.appspot.com',
    iosClientId:
        '355943116384-06qt0ukv927u8ptm5tij3c49cs40vu6c.apps.googleusercontent.com',
    iosBundleId: 'im.concieltalk.app',
  );
}
